export const EventEnums = {
  eventTypes: {
    CASE_CREATED: "CASE_CREATED",
    CASE_ASSIGNED: "CASE_ASSIGNED",
    CASE_UNASSIGNED: "CASE_UNASSIGNED",
    CASE_APPROVED: "CASE_APPROVED",
    TASK_COMPLETED: "TASK_COMPLETED",
    TASK_UPDATED: "TASK_UPDATED",
    STAGE_COMPLETED: "STAGE_COMPLETED",
    NOTE_ADDED: "NOTE_ADDED",
  },
  eventDescriptions: {
    CASE_CREATED: "Case received",
    CASE_ASSIGNED: "Case assigned",
    CASE_UNASSIGNED: "Case unassigned",
    CASE_APPROVED: "Case approved",
    TASK_COMPLETED: "Task completed",
    TASK_UPDATED: "Task updated",
    STAGE_COMPLETED: "Stage completed",
    NOTE_ADDED: "General note added",
  },
  noteDescriptions: {
    NOTE_ADDED: "General",
    TASK_COMPLETED: "Task",
    TASK_UPDATED: "Task",
    STAGE_COMPLETED: "Stage",
    CASE_UNASSIGNED: "Unassignment",
    CASE_ASSIGNED: "Assignment",
    CASE_APPROVED: "Approval",
  },
};
