export const EventEnums = {
  eventTypes: {
    CASE_CREATED: "CASE_CREATED",
    CASE_ASSIGNED: "CASE_ASSIGNED",
    CASE_UNASSIGNED: "CASE_UNASSIGNED",
    TASK_COMPLETED: "TASK_COMPLETED",
    TASK_UPDATED: "TASK_UPDATED",
    PHASE_COMPLETED: "PHASE_COMPLETED",
    STAGE_COMPLETED: "STAGE_COMPLETED",
    CASE_STATUS_CHANGED: "CASE_STATUS_CHANGED",
    NOTE_ADDED: "NOTE_ADDED",
    EXTERNAL_ACTION_TRIGGERED: "EXTERNAL_ACTION_TRIGGERED",
  },
  eventDescriptions: {
    CASE_CREATED: "Case received",
    CASE_ASSIGNED: "Case assigned",
    CASE_UNASSIGNED: "Case unassigned",
    TASK_COMPLETED: "Task completed",
    TASK_UPDATED: "Task updated",
    PHASE_COMPLETED: "Phase completed",
    STAGE_COMPLETED: "Stage completed",
    CASE_STATUS_CHANGED: "Case status changed",
    NOTE_ADDED: "General note added",
    EXTERNAL_ACTION_TRIGGERED: "External action triggered",
  },
  noteDescriptions: {
    NOTE_ADDED: "General",
    TASK_COMPLETED: "Task",
    TASK_UPDATED: "Task",
    STAGE_COMPLETED: "Stage",
    CASE_UNASSIGNED: "Unassignment",
    CASE_ASSIGNED: "Assignment",
    CASE_APPROVED: "Approval",
  },
};
